export const localization = {
  ru: {
    appName: 'Karaoke LRC Maker',
    inputStep: '1. Ввод текста',
    timingStep: '2. Синхронизация и Правка',
    editStep: '3. Экспорт караоке',
    clearConfirm: 'Вы уверены, что хотите очистить проект? Все тайминги и тексты будут безвозвратно удалены.',
    timingProgress: 'ПРОГРЕСС РАЗМЕТКИ СТРОК',
    timingSpaceLabel: 'Нажмите Space в начале этой строки',
    timingWordLabel: 'Нажмите Space на слово',
    allDone: 'Все тайминги расставлены!',
    goToEdit: 'Перейти к редактированию',
    statsTitle: 'Статистика проекта',
    statsTotal: 'Всего строк:',
    statsTimed: 'С таймингом:',
    statsUntimed: 'Без тайминга:',
    statsReady: 'Готовность караоке',
    hotkeysTitle: 'Горячие клавиши',
    hotkeysSpace: 'Поставить тайминг:',
    hotkeysBksp: 'Отменить последний:',
    hotkeysRewind: 'Перемотка -2 сек:',
    hotkeysForward: 'Перемотка +2 сек:',
    hotkeysPlay: 'Старт / Пауза:',
    exportTitle: 'Экспорт субтитров и таймингов',
    exportSubtitle: 'Скачайте файл разметки караоке в любом удобном для вас формате',
    exportCopy: 'Копировать',
    exportCopied: 'Скопировано!',
    exportDownload: 'Скачать',
    exportNoTimings: 'Нет строк с таймингами',
    exportWarning: 'Вы пока не проставили временные метки ни для одной из строк. Перейдите на шаг «Тайминги», чтобы разметить текст под музыку.',
    videoExportTitle: 'Экспорт караоке-видео',
    videoPreviewTitle: 'Окно Предпросмотра Видео',
    videoFormatLabel: 'Формат видео',
    videoStyleLabel: 'Настройки Субтитров и Фона',
    videoBgStyle: 'Стиль Фона',
    videoFont: 'Шрифт текста',
    videoFontSize: 'Размер шрифта (px)',
    videoActiveWordColor: 'Цвет active слова',
    videoStroke: 'Обводка текста',
    videoGlow: 'Свечение тени',
    videoResolution: 'Разрешение видео',
    videoStartExport: 'Начать экспорт видео',
    videoRecording: 'Идет запись видеопотока...',
    videoRecordingProgress: 'Записано:',
    videoRecordingCancel: 'Отменить запись',
    videoRecordingSuccess: 'Экспорт видео успешно завершен! Вы можете просмотреть результат ниже.',
    videoDownload: 'Скачать видео',
    timelineTitle: 'Визуальный Таймлайн-Редактор',
    timelineTip: 'Зажмите и перетаскивайте цветные метки строк горизонтально, чтобы плавно настроить их появление во времени.',
    waveformTitle: 'Навигация & Детектор битов',
    waveformSnap: 'Привязать к биту',
    waveformSnapDone: 'Привязка к биту ✓',
    editorTitle: 'Редактор таймингов',
    editorShiftAll: 'Сдвинуть все тайминги одновременно (сек)',
    editorSetTime: 'Уст. время',
    editorMicrotiming: 'Пословный тайминг (Микрокоррекция слов)',
    editorSplit: 'Разрезать строку: Выберите слово, с которого начнется новая строка',
    editorSplitLabel: 'Разрезать строку',
    editorMerge: 'Склеить со следующей строкой',
    editorDelete: 'Удалить полностью',
    editorReorder: 'Перетаскивание',
    editorNoLines: 'Строки отсутствуют. Введите текст на первом шаге.',
    recentProjectsTitle: 'Список последних проектов',
    recentProjectsDesc: 'Переключайтесь между сохраненными песнями',
    saveProject: 'Сохранить проект',
    enterProjectTitle: 'Введите название проекта',
    projectSaved: 'Проект успешно сохранен!',
    noProjects: 'Нет сохраненных проектов',
    helpModeTitle: 'Режимы синхронизации:',
    helpModeLine: 'Построчно: Нажмите Space в начале строки. Вся строка получит один тайминг.',
    helpModeWord: 'Пословно: Нажмите Space в начале каждого слова. Слова будут плавно подсвечиваться во время воспроизведения (Enhanced LRC).',
    mobileTapArea: 'ТАП ЗОНА ДЛЯ ТЕЛЕФОНА (НАЖМИТЕ ЗДЕСЬ ДЛЯ ТАЙМИНГА)',
    fullscreenLabel: 'Во весь экран',
    
    // Newly added AudioLoader & LyricsInput localization fields
    audioLoaderTitle: 'Аудиофайл загружен',
    audioLoaderPlaceholder: 'Перетащите аудиофайл сюда или кликните для загрузки',
    audioLoaderFormats: 'Поддерживаются форматы MP3, WAV, OGG, M4A (обработка локально в браузере)',
    audioRestoring: 'Восстановление аудиофайла и обложки из кэша...',
    lyricsInputTitle: 'Вставьте текст песни',
    lyricsImportBtn: 'Импортировать Файл (LRC/SRT/VTT/ASS)',
    lyricsHelpText: 'Заголовки вроде "Куплет", "Припев", "[Chorus]" или пустые строки будут автоматически пропущены.',
    lyricsPlaceholder: 'Пример:\nКуплет 1\nЗа окном опять дожди...\nИ мы верим в чудеса...\n\nПрипев\nЭто наше караоке!',
    lyricsPrepareBtn: 'Подготовить строки',
    lyricsQuickStartTitle: 'Быстрый запуск (совет)',
    lyricsQuickStartItem1: 'Вы можете импортировать готовый LRC, SRT, WebVTT или ASS файл субтитров, чтобы автоматически восстановить все строки и тайминги.',
    lyricsQuickStartItem2: 'Используйте простую разметку. Разделители куплетов/припевов помогут вам визуально ориентироваться при вводе, но они будут пропущены при расстановке таймингов, чтобы не мешать ритму.',
    livePlayerLabel: 'ЖИВОЙ ПЛЕЕР',
    timelineTrackLabel: 'Таймлайн трека',
    timelineNoLines: 'Нет строк с таймингами. Сначала расставьте их на вкладке "Тайминги" или загрузите файл.',
    hotkeysCheatsheet: 'Глобальные сочетания клавиш работают на шагах Тайминги и Правка (кроме ввода текста).',
    hotkeysWarning: 'Горячие клавиши активируются после подготовки строк или при переходе к таймингам.',
    exportFilenameLabel: 'Название файла при экспорте',
    exportFilenamePlaceholder: 'Введите название файла...',
    lyricsSearchBtn: 'Поиск текста (LRCLIB)',
    searchModalTitle: 'Поиск текста и таймингов',
    searchQueryPlaceholder: 'Введите название песни и исполнителя...',
    searchBtn: 'Найти',
    searching: 'Идет поиск...',
    searchNoResults: 'Результаты не найдены',
    searchError: 'Не удалось выполнить поиск. Проверьте подключение к сети.',
    searchTitleCol: 'Название',
    searchArtistCol: 'Исполнитель',
    searchAlbumCol: 'Альбом',
    searchDurationCol: 'Длительность',
    searchSyncedBadge: 'Синхр.',
    searchImportSuccess: 'Текст успешно импортирован!',
    searchImportNoSync: 'Внимание: синхронизированный LRC тайминг отсутствует. Импортирован только текст. Хотите разметить тайминги вручную?',
    authTitle: 'Облачный кабинет V2',
    authTelegramLogin: 'Войти через Telegram',
    authMockLogin: 'Тестовый вход (Локально)',
    authLogout: 'Выйти',
    authSyncing: 'Синхронизация...',
    authSynced: 'Облако синхронизировано ✓',
    authSyncError: 'Ошибка синхронизации',
    authGuest: 'Локальный режим (сохранение в браузере)',
  },
  en: {
    appName: 'Karaoke LRC Maker',
    inputStep: '1. Lyrics Input',
    timingStep: '2. Sync & Edit',
    editStep: '3. Export Dashboard',
    clearConfirm: 'Are you sure you want to clear the project? All timings and lyrics will be permanently deleted.',
    timingProgress: 'LYRICS TIMING PROGRESS',
    timingSpaceLabel: 'Press Space at the start of this line',
    timingWordLabel: 'Press Space on word',
    allDone: 'All timings set!',
    goToEdit: 'Go to Editing',
    statsTitle: 'Project Statistics',
    statsTotal: 'Total Lines:',
    statsTimed: 'With Timing:',
    statsUntimed: 'No Timing:',
    statsReady: 'Karaoke Progress',
    hotkeysTitle: 'Keyboard Shortcuts',
    hotkeysSpace: 'Set timestamp:',
    hotkeysBksp: 'Undo last:',
    hotkeysRewind: 'Seek -2 sec:',
    hotkeysForward: 'Seek +2 sec:',
    hotkeysPlay: 'Play / Pause:',
    exportTitle: 'Export Subtitles & Timings',
    exportSubtitle: 'Download karaoke timings in any compatible format',
    exportCopy: 'Copy',
    exportCopied: 'Copied!',
    exportDownload: 'Download',
    exportNoTimings: 'No Timed Lines',
    exportWarning: 'You have not timestamped any lines yet. Go to the "Timing" step to sync lyrics with the track.',
    videoExportTitle: 'Export Karaoke Video',
    videoPreviewTitle: 'Live Video Preview',
    videoFormatLabel: 'Video Format',
    videoStyleLabel: 'Subtitle & Background Settings',
    videoBgStyle: 'Background Style',
    videoFont: 'Text Font',
    videoFontSize: 'Font size (px)',
    videoActiveWordColor: 'Active word color',
    videoStroke: 'Text outline stroke',
    videoGlow: 'Shadow glow',
    videoResolution: 'Video Resolution',
    videoStartExport: 'Start Video Export',
    videoRecording: 'Recording video stream...',
    videoRecordingProgress: 'Recorded:',
    videoRecordingCancel: 'Cancel Recording',
    videoRecordingSuccess: 'Video export completed successfully! Preview the result below.',
    videoDownload: 'Download Video',
    timelineTitle: 'Visual Timeline Editor',
    timelineTip: 'Hold and drag the colored tags horizontally to adjust their timestamps in time.',
    waveformTitle: 'Navigation & Beat Detector',
    waveformSnap: 'Snap to beat',
    waveformSnapDone: 'Snap to beat ✓',
    editorTitle: 'Timing Editor',
    editorShiftAll: 'Shift all timings simultaneously (sec)',
    editorSetTime: 'Set time',
    editorMicrotiming: 'Word Timings (Micro-corrections)',
    editorSplit: 'Split line: Select the word that will start the new line',
    editorSplitLabel: 'Split line',
    editorMerge: 'Merge with next line',
    editorDelete: 'Delete line',
    editorReorder: 'Drag handles',
    editorNoLines: 'No lyric lines found. Input lyrics on step 1.',
    recentProjectsTitle: 'Recent Projects',
    recentProjectsDesc: 'Switch between saved songs',
    saveProject: 'Save Project',
    enterProjectTitle: 'Enter project title',
    projectSaved: 'Project saved successfully!',
    noProjects: 'No saved projects yet',
    helpModeTitle: 'Sync Modes:',
    helpModeLine: 'Line-by-line: Press Space at the start of each line. The whole line gets one timestamp.',
    helpModeWord: 'Word-by-word: Press Space at the start of each word. Words highlight progressively (Enhanced LRC).',
    mobileTapArea: 'MOBILE TAP AREA (TOUCH HERE TO SET TIMESTAMP)',
    fullscreenLabel: 'Fullscreen',
    
    // Newly added AudioLoader & LyricsInput localization fields
    audioLoaderTitle: 'Audio Track Loaded',
    audioLoaderPlaceholder: 'Drag & drop an audio file here or click to load',
    audioLoaderFormats: 'Supported formats: MP3, WAV, OGG, M4A (processed fully client-side)',
    audioRestoring: 'Restoring audio track and cover art from cache...',
    lyricsInputTitle: 'Paste song lyrics below',
    lyricsImportBtn: 'Import Subtitle File (LRC/SRT/VTT/ASS)',
    lyricsHelpText: 'Headers (like "Verse", "Chorus", "[Chorus]") and blank lines will be skipped automatically.',
    lyricsPlaceholder: 'Example:\nVerse 1\nUnderneath the summer skies...\nWhere the quiet water lies...\n\nChorus\nThis is our karaoke!',
    lyricsPrepareBtn: 'Prepare Lyric Lines',
    lyricsQuickStartTitle: 'Quick Start Tips',
    lyricsQuickStartItem1: 'You can import pre-existing LRC, SRT, WebVTT, or ASS subtitle files to automatically recover all lyrics and timestamps.',
    lyricsQuickStartItem2: 'Use simple spacing. Section separators will help you visually organize lyrics, but they will be filtered out to keep timing smooth.',
    livePlayerLabel: 'LIVE PLAYER',
    timelineTrackLabel: 'Track Timeline',
    timelineNoLines: 'No timed lines. Set timings in the "Timing" step first or import a subtitle file.',
    hotkeysCheatsheet: 'Global hotkeys work on the Timing and Edit screens (except inside textboxes).',
    hotkeysWarning: 'Hotkeys will be activated after preparing lyrics or switching steps.',
    exportFilenameLabel: 'Export filename',
    exportFilenamePlaceholder: 'Enter filename...',
    lyricsSearchBtn: 'Search Lyrics (LRCLIB)',
    searchModalTitle: 'Search Lyrics & Timings',
    searchQueryPlaceholder: 'Enter song title and artist...',
    searchBtn: 'Search',
    searching: 'Searching...',
    searchNoResults: 'No results found',
    searchError: 'Search failed. Please check your internet connection.',
    searchTitleCol: 'Title',
    searchArtistCol: 'Artist',
    searchAlbumCol: 'Album',
    searchDurationCol: 'Duration',
    searchSyncedBadge: 'Synced',
    searchImportSuccess: 'Lyrics imported successfully!',
    searchImportNoSync: 'Warning: synchronized LRC timing is not available. Only plain text was imported. Would you like to set timings manually?',
    authTitle: 'V2 Cloud Account',
    authTelegramLogin: 'Login with Telegram',
    authMockLogin: 'Mock Login (Local)',
    authLogout: 'Logout',
    authSyncing: 'Syncing...',
    authSynced: 'Cloud synced ✓',
    authSyncError: 'Sync error',
    authGuest: 'Local mode (saved in browser)',
  }
};
